<a href="https://colab.research.google.com/github/ElmiraOn/EECS6322-Global-Rhythm-Style-TransferWithout-Text-Transcriptions/blob/main/6322_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoder Architecture

8 layer 1 D convolutional network where each later uses 5x1 filters wuth 1 stride, SAME oadding and ReLu actiuvation. GroupNorm is applierd to every layer. the number of flliters is 512 and first five layers and last three have 128, 32, 4 filters respectivly.

input: 13 D MFCC

The encoder output dimension is set to four.

# Implementation

## imports

In [1]:
import torch
from torchvision import datasets
from torchvision import transforms
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Conv1D, ReLU, GroupNormalization

In [13]:
tensor_transform = transforms.ToTensor()

In [43]:
class Encoder():
    def __init__(self):
        self.layers = []
        for i in range(5): # first 5 layers have 512 filters
          conv = Conv1D(filters=512, kernel_size=5, strides=1, padding='same', activation='relu')
          group = GroupNormalization(groups=512)
          self.layers.append(conv)
          self.layers.append(group)

        conv6 = Conv1D(filters=128, kernel_size=5, strides=1, padding='same', activation='relu')
        group6 = GroupNormalization(groups=128)
        self.layers.append(conv6)
        self.layers.append(group6)

        conv7 = Conv1D(filters=32, kernel_size=5, strides=1, padding='same', activation='relu')
        group7 = GroupNormalization(groups=32)
        self.layers.append(conv7)
        self.layers.append(group7)

        conv8 = Conv1D(filters=4, kernel_size=5, strides=1, padding='same', activation='relu')
        group8 = GroupNormalization(groups=4)
        self.layers.append(conv8)
        self.layers.append(group8)

    def forward(self, x):
        for layer in self.layers:
          x = layer(x)
        return x


In [44]:
input_shape = tf.random.normal((1, 13, 1)) # Assuming 1D input

# Create the encoder model
encoder_model = Encoder()
output = encoder_model.forward(input_shape)
print(output)


tf.Tensor(
[[[-0.72563845  1.5047582  -0.9092516  -0.30174088]
  [-0.72563845 -0.85222924 -0.9092516   0.34600472]
  [ 0.36987168 -0.1002211  -0.9092516   2.3927398 ]
  [ 1.2746978  -0.85222924  0.05415952 -0.82459414]
  [-0.72563845 -0.85222924  0.87301874 -0.82459414]
  [-0.72563845 -0.85222924  0.17037296 -0.82459414]
  [ 1.7424219  -0.5662582   1.5465783   0.45005596]
  [-0.72563845 -0.85222924  2.1356297   1.3674937 ]
  [-0.72563845  1.5693444   0.20181656 -0.82459414]
  [ 0.48249966  0.5781536  -0.9092516   0.9141388 ]
  [-0.72563845 -0.85222924  0.4739324  -0.22112662]
  [-0.72563845  0.37166727 -0.9092516  -0.82459414]
  [ 1.9356172   1.7559313  -0.9092516  -0.82459414]]], shape=(1, 13, 4), dtype=float32)
